#+TITLE:   Fondements de la programmation lambda-calcul
#+AUTHOR:   Pierre Boudes
#+EMAIL:    boudes@univ-paris13.fr

#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  fr
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc toc:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+LINK_UP:
#+LINK_HOME:
#+XSLT:
#+STARTUP: latex nolatexpreview entitiesplain
#+LaTeX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt, a4paper]
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}
#+LATEX_HEADER: \usepackage[table]{xcolor}
#+LATEX_HEADER: \usepackage{xspace}
#+LATEX_HEADER: \usepackage{multicol}
#+LATEX_HEADER: \usepackage{bussproofs}
#+LATEX_HEADER: \usepackage{tikz}\usetikzlibrary{arrows,shapes,trees}
#+LATEX_HEADER: \renewcommand{\maketitle}{{\bigskip{\begin{center}\Large\textbf{Fondements de la programmation}\\[0.1cm] Exercices 9 lambda-calcul\end{center}}}\smallskip}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[french]{babel}
#+EXCLUDE_TAGS: noexport correction

#+BEGIN_LaTeX
\EnableBpAbbreviations
\pagestyle{fancyplain}
\fancyhf{}
\lhead{ \fancyplain{}{$\vcenter{\hbox{\includegraphics[scale=0.12]{../img/Logo_SPC.jpg}}}$ Institut Galilée. P. Boudes, J. Le Roux et V. Mogbil}}
\rhead{ \fancyplain{}{Master 1 informatique 2015-2016}}
\rfoot{ \fancyplain{}{\thepage}}
%\rfoot{ }
\newcounter{questioncount}
\setcounter{questioncount}{0}
\newcommand{\question}[1][]{\addtocounter{questioncount}{1}\paragraph{Question \Alph{questioncount}. #1}}
\renewcommand{\subsubsection}[1]{\question[#1.]}
\newcommand{\tabDP}{\shortstack{\smallskip\\\DisplayProof\smallskip}}
\newcommand{\eqdef}{\mathrel{\shortstack{\scriptsize\text{def}\\=}}}
#+END_LaTeX




#+BEGIN_LaTeX
\begin{multicols}{2}
#+END_LaTeX

Stratégie d'évaluation : *appel par valeur.* Nous allons maintenant restreindre la
$\beta$-réduction de façon à ce qu'elle corresponde à la façon dont
les programmes sont évalués dans la plupart des langages de
programmation. On distingue un ensemble particulier de termes appelés
valeurs au delà desquels on ne (\beta-)réduit plus. En l'absence
d'extensions du lambda-calcul, qui viendront après, les valeurs sont
tous les termes qui correspondent à une abstraction :
\[
v := \lambda x. t
\]
Intuitivement, on ne réduit pas dans le corps des fonctions tant
qu'elles ne sont pas complètement appliquées.
#+BEGIN_COMMENT
 En Caml, on ne réduira pas l'expression
#+BEGIN_SRC ocaml
let add10 x y = 10 * x + y in
    add10 3
#+END_SRC
avant de donner une valeur au deuxième paramètre, y.
#+END_COMMENT

On se donne
ensuite des règles d'évaluation qui déterminent exactement l'ordre dans
lequel il faut faire les réductions dans un terme.
#+BEGIN_LaTeX
  \begin{gather*}
  \AXC{}
  \UIC{$(\lambda x. t_1\; v_2) \to t_1[x:=v_2]$}\tabDP\\
    \AXC{$t_1 \to t'_1$}
    \UIC{$(t_1\; t_2)\to (t'_1\; t_2)$}
  \tabDP\quad
    \AXC{$t_2 \to t'_2$}
    \UIC{$(v_1\; t_2)\to (v_1\; t'_2)$}
  \tabDP
  \end{gather*}
#+END_LaTeX

Le point important dans cet ensemble de règles est qu'il n'y a pas de
règle qui permette de réduire sous une abstraction.

Nous reviendrons plus en détails sur les différentes stratégies
d'évaluation possibles.


Nous allons maintenant
donner des *extensions du lambda-calcul* *simplement typé* de façon à en
faire un langage de programmation, Turing-complet et ayant les
caractéristiques d'un langage de type ML (les langages ML comme SML,
CAML sont inspirés des extensions du lambda-calcul et en particulier
du langage PCF, /programming/ /computable/ /functions/).

*Unit*. On ajoute un terme
~unit~ qui sera aussi une valeur, et son type, ~Unit~.
#+BEGIN_LaTeX
  \begin{align*}
    t &:= \ldots \mid \texttt{unit}\\
    v &:= \ldots \mid \texttt{unit}\\
    T &:= \ldots \mid \texttt{Unit}
  \end{align*}
  \begin{gather*}
    \AXC{}
    \UIC{$\Gamma \vdash   \texttt{unit} : \texttt{Unit}$}\DP
  \end{gather*}

#+END_LaTeX
Ceci nous permet d'introduire une /forme dérivée/:
#+BEGIN_LaTeX
\[
t_1;t2 \eqdef (\lambda x[\texttt{Unit}]. t_2\;\; t_1)\quad (x\notin FV(t_2)).
\]
#+END_LaTeX
Cette mise en séquence, $t_1; t_2$ a pour effet d'évaluer
$t_1$, de jeter son résultat, puis d'évaluer $t_2$. Les règles
d'évaluation et de typage induites sur la forme sont :
#+BEGIN_LaTeX
  \begin{gather*}
  \AXC{$t_1\to t'_1$}
  \UIC{$t_1; t_2\to t'_1; t_2$}
  \tabDP\quad
  \AXC{}
  \UIC{$\texttt{unit}; t_2 \to t_2$}\tabDP
  \\
  \AXC{$\Gamma \vdash t_1 : \texttt{Unit}$}
  \AXC{$\Gamma \vdash t_2: T_2$}
  \BIC{$\Gamma \vdash t_1; t_2: T_2$}\tabDP
  \end{gather*}
#+END_LaTeX

*Let in*.  On peut également se donner la forme syntaxique \texttt{let in}
#+BEGIN_LaTeX
    \begin{gather*}
     t := \ldots \mid \texttt{let }x = t\texttt{ in } t\\
    \AXC{}
    \UIC{$\texttt{let }x = v_1\texttt{ in } t_2 \to t_2[x := v_1]$}\tabDP\\
    \AXC{$t_1 \to t'_1$}
    \UIC{$\texttt{let }x = t_1\texttt{ in } \to \texttt{let }x = t'_1\texttt{ in } t_2 $}\tabDP\\
  \AXC{$\Gamma \vdash t_1: T_1$}
  \AXC{$\Gamma, x : T_1 \vdash t_2: T_2$}
  \BIC{\Gamma\vdash \texttt{let }x = t_1\texttt{ in } t_2 :  T_2$}
  \tabDP
    \end{gather*}
#+END_LaTeX

Au premier abord, cette forme $\texttt{let }x = t_1\texttt{ in } t_2$
est juste du sucre syntaxique pour $(\lambda x: T_1. t_2\; t_1)$. Pour
/désugariser/ il faudra toutefois trouver l'annotation de type pour
$\lambda x$, donc faire l'inférence de type avant.

*Combinateur de point fixe*. Pour chaque type $T_1$ on se donne
 un  opérateur sur les termes ~fix~ tel que :
#+BEGIN_LaTeX
\newcommand{\fix}{\mathop{\texttt{fix}}}
  \begin{gather*}
    t := \ldots \mid (\fix\; t)\\
  \AXC{}
  \UIC{$(\fix \;\lambda x[T_1]. t_2) \to t_2 [x:=(\fix \;\lambda x[T_1]. t_2)]$}\tabDP\\
  \AXC{$t_1 \to t'_1$}
  \UIC{$\fix\; t_1 \to \fix\; t'_1$}\tabDP\\
\AXC{$\Gamma \vdash t_1: T_1\to T_1$}
\UIC{$\Gamma \vdash (\fix \; t_1): T_1$}
\tabDP  \end{gather*}
#+END_LaTeX

Forme dérivée:
#+BEGIN_LaTeX
  \begin{align*}
 &\texttt{letrec } x =  t_1 \texttt{ in }   t_2 \\
&\eqdef
  \texttt{let } x = (\fix \;\lambda x[T_1]. t_1) \texttt{ in }   t_2
  \end{align*}
#+END_LaTeX

* plus tard :noexport:

*Annotation d'un terme par un type* (/ascription/). TODO

** Combinateur de point fixe Y de Church
Soit :
#+BEGIN_LaTeX
\begin{gather*}
   Y = \lambda f.(\lambda x.f (x\; x)) (\lambda x.f (x\; x))
  \end{gather*}
#+END_LaTeX
Dans le lambda-calcul pur, pour $f$ terme quelconque, montrer que $(Y f) \equiv_{\beta} (f (Y f))$.

*** Solution
On montre que $(Y\; f)$ est $\beta$ equivalent à $(f (Y
f))$, c'est à dire qu'il y a un terme en lequel se réduisent chacun de
ces deux termes.
#+BEGIN_LaTeX
  \begin{align*}
    (Y\; f)&= (\lambda f.(\lambda x.f (x\; x)) (\lambda x.f (x\; x))\;
    f)\\
  &\to_{\beta} \underbrace{((\lambda x.f (x\; x))\; (\lambda x.f (x\; x)))}_{t}\\
  &\to_{\beta} (f \; \underbrace{((\lambda x.f (x\; x))\;(\lambda x.f (x\; x)))}_{t})
  \end{align*}
#+END_LaTeX
On a $(Y\; f)\to_{\beta}  t$, donc $(f\;(Y\; f))\to_{\beta} (f\; t)$
et $(Y\; f)\to_{\beta} (f\; t)$ donc ces deux termes sont $\beta$-équivalents.

** Fonction récursive en lambda-calcul
Définir la fonction factorielle en lambda-calcul pur (sur les entiers
de Church). Indication : cette fonction doit être le point fixe d'un
fonction définie par cas.

*** Solution
On pose $h = \lambda gn. \operatorname{ifthenelse}\;
(\operatorname{iszero}\; n)\; \underline{1}\; (\operatorname{mult}\; n \; (g \; (\operatorname{pred}
\; n)))$. On a alors que factorielle est le terme $\operatorname{fact}
= (Y\; h)$. On vérifie le fonctionnement sur des exemples
comme  $(\operatorname{fact} 0)$ et $(\operatorname{fact} 2)$ ou  $(\operatorname{fact} 3)$. Puis plus
formellement on établit que  $\operatorname{fact} \underline{0}$ et $\operatorname{fact} \underline{n + 1}$
sont $\beta$-équivalents respectivement à $\underline{1}$ et à
$(\operatorname{mult}\;\underline{n + 1} \; (\operatorname{fact}\; \underline{n}))$.
